---
- hosts: MultiPurposeServer
  become: yes
  tasks:
        - import_tasks: tasks/essential_debian.yml
        - name: Ensure dependencies are installed
          apt:
                name:
                        - docker
                        - docker-compose
                state: present
        - name: Ensure python dependencies are installed
          pip:
                name:
                        - docker
                state: present
        - name: Ensuring obico repo is cloned
          ansible.builtin.git:
                repo: 'https://github.com/TheSpaghettiDetective/obico-server.git'
                dest: /root/obico
        - name: deploy obico via docker compose
          docker_compose:
                project_src: /root/obico/